/**
 * @author John Muller
 */
package eu.johnmuller.ecaperooms.Views;

import eu.johnmuller.ecaperooms.Classes.Greetings;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class AboutForm extends javax.swing.JFrame {

    // get username from the login form
    // this way did not work so i set this variable (username) as public
    // and i access it from Login form and set its value but left this here
    // so it shows how i would have done it in another language
    public static String username = new LoginForm().getUsername();

    // get greetings according to the current time
    String greetings = Greetings.Display();

    // set custom logo
    ImageIcon logo = new ImageIcon(".//Assets//Images//Logo.png");

    public AboutForm() {
        initComponents();

        // dispose (close) the current form only! 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // set labels according to thier data 
        greetingsLbl.setText(greetings);
        usernameLbl.setText(username);
        this.setIconImage(logo.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        backgroundImagePanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        greetingsLbl = new javax.swing.JLabel();
        backgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escape Rooms");
        setPreferredSize(new java.awt.Dimension(900, 450));
        setResizable(false);

        backgroundImagePanel.setLayout(null);

        usernameLbl.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 1, 30)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(27, 105, 120));
        usernameLbl.setText("John Muller");
        usernameLbl.setVerticalAlignment(0);
        backgroundImagePanel.add(usernameLbl);
        usernameLbl.setBounds(270, 110, 320, 40);

        greetingsLbl.setFont(new java.awt.Font("Montserrat Alternates SemiBold", 1, 30)); // NOI18N
        greetingsLbl.setForeground(new java.awt.Color(236, 236, 236));
        greetingsLbl.setText("Good Morning");
        backgroundImagePanel.add(greetingsLbl);
        greetingsLbl.setBounds(20, 110, 250, 40);

        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(".//Assets//Images//AboutPage .png")); // NOI18N
        backgroundImagePanel.add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, -10, 910, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(backgroundImagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(backgroundImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE));

        pack();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            new AboutForm().setVisible(true);
        });

    }

    private javax.swing.JPanel backgroundImagePanel;
    private static javax.swing.JLabel backgroundImageLabel;
    private static javax.swing.JLabel greetingsLbl;
    private static javax.swing.JLabel usernameLbl;
}
